name: nanomethphase
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.7.7
  - r-base>=3.6.0
  - numpy>=1.18.1
  - pysam>=0.15.4
  - pytabix>=0.0.2
  - tabix>=0.2.6
  - tqdm>=4.44.1
  - r-r.utils>=2.8.0
  - bioconductor-dss>=2.36.0
  - r-sys>=3.2
