name: nanomethphase
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - r-base
  - numpy
  - pysam
  - pytabix
  - tabix
  - tqdm
  - r-r.utils
  - r-sys
  - bioconductor-dss
