name: nanomethphase
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - r-base
  - numpy
  - pysam
  - pytabix
  - tabix
  - tqdm
  - r-r.utils>=2.8.0
  - r-sys>=3.2
  - bioconductor-dss
